### ISSUE TITLE
Character load

### ISSUE THREAD

**Issue by arthurpaulino** [DungeonPaper/dungeon-paper-app#12]
The character load is calculated using the attribute value itself instead of the modified. For instance, the wizard has a load of 7+Str (notice that it doesn't say "STR", with capital letters), so, even if strength is the lowest wizard's attribute, with a value of 8 (modifier -1), its load would be 15 and not 6. Source: [Dungeon World SRD](https://www.dungeonworldsrd.com/classes/wizard/).

Another detail is that a wizard starts with a Spellbook, which takes a load of 1. There might be other classes that necessarily start with items.

**Comment by chenasraf** [comment]
Yes, a small mistake I made while implementing this.

> Another detail is that a wizard starts with a Spellbook, which takes a load of 1. There might be other classes that necessarily start with items.

What's the problem with that though? Once the count is fixed, that should be ok, right? Or do these items not count towards the total weight?

**Comment by arthurpaulino** [comment]
They count. The problems are:
1. The Wizard doesn't start with a spellbook in the app
2. There is no spellbook in the item list, so we always need to create a custom item

**Comment by chenasraf** [comment]
I see. Looks like I should add the spell book to the built-in inventory list.

**Comment by arthurpaulino** [comment]
@chenasraf what do you think about also making wizards automatically start with a spellbook?

**Comment by chenasraf** [comment]
I'm not against the idea, but it should be considered how it's done. There is already data about starting gear options and choices, I was thinking these could possibly be connected. 
Right now that data isn't used at all in the app.

I don't think a special case for 1 built-in class would be ideal, I think it will lead to some odd solutions and code placements. I'd rather do something more generic so that it can be used for other classes as well.

**Comment by arthurpaulino** [comment]
Yeah I saw that starting gear data yesterday. It would be definitely a better place to put such items.

**Comment by chenasraf** [comment]
Fixed in 85a5330a3c076aea89a91c999e4f46c6db959ce2
